import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Hackathon App",
  description: "Generated by Trae",
};

import SplashScreenHandler from "@/components/SplashScreenHandler";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SplashScreenHandler />
        {children}
      </body>
    </html>
  );
}
